[command]
default=$CYLC_SUITE_RUN_DIR/bin/extract_xios.sh
git=$CYLC_SUITE_RUN_DIR/bin/extract_xios_git.sh

[file:bin/extract_xios.sh]
source=$CYLC_SUITE_RUN_DIR/bin/extract_xios.sh

[file:bin/extract_xios_git.sh]
source=$CYLC_SUITE_RUN_DIR/bin/extract_xios_git.sh
