[template variables]
BUILD_MCT=true
BUILD_TEST=true
EXTRACT_OASIS=true
GC_PRG_ENV_NAME='GC6-PrgEnv'
GC_PRG_ENV_VERSION='test_x3_coupled_20260306'
HPC_HOST='exab'
HPC_HOST_USERNAME='harry.shepherd'
MODULE_CMD='module use /common/internal/spack/releases/2025.10.1/ngms; module use /data/users/mark.hedley/modules/linux-sles15-x86_64/cce/15.0.0; module use /data/users/mark.hedley/modules/linux-sles15-x86_64/cray-mpich/8.1.27-aaisa7i/cce/15.0.0; module switch PrgEnv-cray PrgEnv-cray/8.4.0; module load cpe/23.09; module switch cce cce/15.0.0; module load lfric-cray/15.0.0/3.0+ || true; module load zlib-ng/2.2.1-qc6q62y glibc/2.31-2gykboy || true; module load pkg-config/0.29.2-hxxl2mu || true; module unload hdf5 || true; module unload netcdf-c || true; module unload netcdf-fortran || true; module unload xios || true; module load cray-hdf5-parallel; module load cray-netcdf-hdf5parallel; module list'
OASIS_BRANCH='b427e1d5'
OASIS_BUILD_DIR='crayEX'
OASIS_MOD_NAME='oasis3-mct_4.0'
OASIS_MOD_VERSION='test_x3_coupled_20260306'
OASIS_REPOSITORY='https://gitlab.com/cerfacs/oasis3-mct.git'
!!OASIS_WC_DIR='/data/users/hshep/oasis_srcs/oasis3-mct'
PLATFORM_CONFIG='make.crayEX'
XIOS_GIT=true
XIOS_GIT_REPOSITORY='https://gitlab.in2p3.fr/ipsl/projets/xios-projects/xios.git'
XIOS_HASH='abeb3fe6e09465b822c82c99096a736bab9555b3'
XIOS_MOD_NAME='XIOS-2.0'
XIOS_MOD_VERSION='test_x3_coupled_20260306'
XIOS_ONLY=false
!!XIOS_PRG_ENV_NAME='XIOS_2.5-PrgEnv'
!!XIOS_PRG_ENV_VERSION='2023-03-ticket613-cpe22.11'
!!XIOS_REV=2701
!!XIOS_URL='fcm:xios2.xm'
!!XIOS_VERSION='trunk'
