[template variables]
!!BUILD_MCT=true
!!BUILD_TEST=true
!!EXTRACT_OASIS=true
!!GC_PRG_ENV_NAME='GC6-PrgEnv_ngarch'
!!GC_PRG_ENV_VERSION='2026-06-ngarch-cpe23.05-mpich8.1.27'
HPC_HOST='excd'
HPC_HOST_USERNAME='harry.shepherd'
MODULE_CMD='module use /common/internal/spack/releases/2026.7.1/ngms; module switch PrgEnv-cray PrgEnv-cray/8.4.0; module load cpe/23.05; module switch cce cce/15.0.0; module load cray-mpich/8.1.27; module load lfric-cray/15.0.0/3.2 || true; module unload xios/2.2701 || true; module load cray-hdf5-parallel; module load cray-netcdf-hdf5parallel; module list'
!!OASIS_BRANCH='b427e1d5'
!!OASIS_BUILD_DIR='crayEX'
!!OASIS_MOD_NAME='oasis3-mct_4.0'
!!OASIS_MOD_VERSION='2026-06-ngarch-cpe23.05-mpich8.1.27'
!!OASIS_REPOSITORY='https://gitlab.com/cerfacs/oasis3-mct.git'
!!OASIS_WC_DIR='/data/users/hshep/oasis_srcs/oasis3-mct'
!!PLATFORM_CONFIG='make.crayEX'
XIOS_GIT=true
XIOS_GIT_REPOSITORY='https://github.com/MetOffice/tcd-XIOS2-extras.git'
XIOS_HASH='ce196b96e166e6bd1e5894a605278fd35e29f1e7'
XIOS_MOD_NAME='XIOS-2.0'
XIOS_MOD_VERSION='2026-09-ngarch-cpe23.05-quantize'
XIOS_ONLY=true
XIOS_PRG_ENV_NAME='XIOS_2.0-PrgEnv'
XIOS_PRG_ENV_VERSION='2026-09-ngarch-cpe23.05-quantize'
!!XIOS_REV=2701
!!XIOS_URL='fcm:xios2.xm'
!!XIOS_VERSION='trunk'
